****Naïve Bayes Classifier Algorithm****

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

***Load the Dataset***

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/Enjoy sports.csv')
df.head()

Day   Outlook Temp. Humidity    Wind Decision
0    1     Sunny   Hot     High    Weak       No
1    2     Sunny   Hot     High  Strong       No
2    3  Overcast   Hot     High    Weak      Yes
3    4      Rain  Mild     High    Weak      Yes
4    5      Rain  Cool   Normal    Weak      Yes

In [ ]:
X = df.iloc[:, 1:-1]
y = df.iloc[:, -1]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X = X.apply(le.fit_transform)
y = le.fit_transform(y)

In [ ]:
X.head()

Outlook  Temp.  Humidity  Wind
0        2      1         0     1
1        2      1         0     0
2        0      1         0     1
3        1      2         0     1
4        1      0         1     1

**Split the Data**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Train an Naïve Bayes Classifier Model**

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

**Evaluate the Model**

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred = nb.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Error:", 1 - accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred))

Accuracy: 1.0
Error: 0.0
Confusion Matrix:
 [[1 0]
 [0 3]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [ ]:
print("Prediction | Actual_test")
print(y_pred)
print(y_test)

Prediction | Actual_test
[1 1 0 1]
[1 1 0 1]
